services:

  registration-service:
    container_name: registration-service
    build:
      context: launcher
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    environment:
      JWT_AUDIENCE: http://localhost:8181/api
    ports:
      - "8181:8181"
      - "5005:5005"
  did-server:
    container_name: did-server
    image: nginx
    volumes:
     - ./resources/webdid:/usr/share/nginx/html
    ports:
     - "8080:80"
