openapi: 3.0.1
info:
  title: Eclipse Dataspace Connector Registration Service
  version: 0.0.1
paths:
  /registry/participant:
    post:
      description: Asynchronously request to add a dataspace participant.
      operationId: addParticipant
      parameters:
      - in: header
        name: IdsUrl
        schema:
          type: string
      responses:
        "204":
          description: No content
      tags:
      - Registry
  /registry/participant/status:
    get:
      description: Gets status of a participant by DID.
      operationId: getParticipantStatus
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantDto'
          description: Dataspace participant.
        "404":
          description: Dataspace participant not found.
      tags:
      - Registry
  /registry/participants:
    get:
      description: Gets all dataspace participants.
      operationId: listParticipants
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ParticipantDto'
          description: Dataspace participants.
      tags:
      - Registry
components:
  schemas:
    ParticipantDto:
      type: object
      properties:
        did:
          type: string
        name:
          type: string
        status:
          type: string
          enum:
          - AUTHORIZING
          - AUTHORIZED
          - DENIED
        supportedProtocols:
          type: array
          items:
            type: string
        url:
          type: string
