name: Test Code (Style, Tests)

on:
  push:
jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/gradle-setup

      - name: 'Unit and system tests'
        run: ./gradlew test

